web/router.ex
defmodule ChatterboxHost.Router do
  use ChatterboxHost.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatterboxHost do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registrations", RegistrationController, only: [:new, :create]
    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
  end

  forward "/consult", Consult.Routes
end

web/views/layout_view.ex
defmodule ChatterboxHost.LayoutView do
  use ChatterboxHost.Web, :view
end

web/templates/layout/_chatbox.html.eex
<div id="chatbox" class="inactive <%= assigns[:chatbox_class]%>" data-conversation-id="<%= assigns[:conversation_id] %>">
  <div class="active state">
    <div class="chatbox-label">
      Live Chat, woo!
      <button id="chatbox-close-chat">✗</button>
    </div>
    <div id="chatbox-messages" tabindex="0">
    </div>
    <form>
      <textarea id="chatbox-input" placeholder="type here"></textarea>
    </form>
  </div>
  <div class="inactive state">
    <button id="chatbox-startchat"></button>
  </div>
  <div class="loading state">
    Loading...
  </div>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ChatterboxHost!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <%= if logged_in?(@conn) do %>
          <li><%= current_user(@conn).email %></li>
          <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
        <% else %>
          <li><%= link "Login",    to: "/login" %></li>
          <li><%= link "Register", to: registration_path(@conn, :new) %></li>
        <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <%= render ChatterboxHost.LayoutView, "_chatbox.html" %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>